.TH "GIT-message-length" 1 "September 25 2024" "git-message-length 1.1.1" "User Commands"
.SH NAME
git-message-length \- Check a commit's message's length
.SH SYNOPSIS

\fBgit message-length\fR [\fB\-\-log-level\fR=\<\fIlog level\fR\>] [\<\fIrevision\fR\>]

\fBgit message-length\fR (\fBhelp\fR | \fB--help\fR)

\fBgit message-length\fR (\fB--version\fR | \fB-v\fR | \fBversion\fR)

.SH DESCRIPTION
\fBgit-message-length\fR Check a commit's message's length.

.SH COMMANDS
The following commands are available:

.IP \(bu
\fBgit message-length\fR [\fB\-\-log-level\fR=\<\fIlog level\fR\>] [\<\fIrevision\fR\>]

Check a commit's message's length.

Succeeds if the message is 72 characters long, or shorter.

Fails if the message is 73 characters long, or longer.

\<\fIrevision\fR\> is any revision parameter accepted by \`git log -1\`.

If the log level (default 3) is 0, the command has no output.

If the log level (default 3) is 1, only the integer length of the commit
message is logged.

If the log level (default 3) is 2 or 3, the length of the commit message is
logged in a sentence, colored yellow if the message is between 50 and 72
characters long, colored red if the message is more than 72 characters long.

If the log level is 3 (default) the commit message is logged. Characters 51-72
are highlighted in yellow. Characters after 72 are highlighted in red.

.IP \(bu
\fBgit message-length\fR (\fBhelp\fR | \fB--help\fR)

Show this document.

.IP \(bu
\fBgit message-length\fR (\fB--version\fR | \fB-v\fR | \fBversion\fR)

Show the current version.

.SH CONFIGURATION

Configure git-message-length in the \fBmessage-length\fR git-config
section.

Set options with \`git config [--global] message-length.<key> <value>\`.

.IP \(bu
\fBerrorafter\fR

The message length after which git-message-length errors.
72 if not otherwise configured.

.IP \(bu
\fBloglevel\fR

The default log level. Supported values are 0, 1, 2, and 3.
3 if not otherwise configured.

.IP \(bu
\fBwarnafter\fR

The message length after which git-message-length errors.
50 if not otherwise configured.

.SH AUTHORS

Henry Bley\-Vroman <olets@olets.dev>
